### ISSUE TITLE
SadConsole Engine

### ISSUE THREAD

**Issue by Thraka** [Vercuski/Game#1]
Hi!

I was just browsing people doing ascii type stuff and found your project. I've been working on an ascii-style game engine for a long time now and it's available at https://github.com/Thraka/SadConsole

You should be able to just compile the entire engine no problem. There is a StarterProject folder that shows how to do lots of things with the engine and even shows how to have a little guy walk around.

Cheers!

**Comment by Vercuski** [comment]
Hi Andy !

Thank you !!! I downloaded and looked at your console ... looks awesome !!!!

I just started this a few days ago, screwing around in my spare time with
console gaming. Took inspiration from an old set of Commodore 64 games
("Legacy of the Ancients" and "Legend of Blacksilver"). I just wanted to
see what I could do with the console.

I appreciate you sharing the codebase with me !

Thanks,

**Comment by Thraka** [comment]
One of my goals long ago was to be able to replicate the C64 screen using a C64-styled font and colors. :)

**Comment by Vercuski** [comment]
that's excellent ! I hope get my lil console to a reasonably reusable
standpoint ... unfortunately between work, kids and work my time is limited.

**Comment by Thraka** [comment]
That is always the problem ;)
